/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 19
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 16
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 8
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__start = 1,
  sym__range_start = 2,
  sym__run = 3,
  sym__tail = 4,
  sym__open = 5,
  sym__close = 6,
  sym__text = 7,
  sym__range_text = 8,
  sym_prose = 9,
  sym_url = 10,
  sym__part = 11,
  sym__group = 12,
  aux_sym_prose_repeat1 = 13,
  aux_sym_url_repeat1 = 14,
  aux_sym__group_repeat1 = 15,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__start] = "_start",
  [sym__range_start] = "_range_start",
  [sym__run] = "_run",
  [sym__tail] = "_tail",
  [sym__open] = "_open",
  [sym__close] = "_close",
  [sym__text] = "_text",
  [sym__range_text] = "_range_text",
  [sym_prose] = "prose",
  [sym_url] = "url",
  [sym__part] = "_part",
  [sym__group] = "_group",
  [aux_sym_prose_repeat1] = "prose_repeat1",
  [aux_sym_url_repeat1] = "url_repeat1",
  [aux_sym__group_repeat1] = "_group_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__start] = sym__start,
  [sym__range_start] = sym__range_start,
  [sym__run] = sym__run,
  [sym__tail] = sym__tail,
  [sym__open] = sym__open,
  [sym__close] = sym__close,
  [sym__text] = sym__text,
  [sym__range_text] = sym__range_text,
  [sym_prose] = sym_prose,
  [sym_url] = sym_url,
  [sym__part] = sym__part,
  [sym__group] = sym__group,
  [aux_sym_prose_repeat1] = aux_sym_prose_repeat1,
  [aux_sym_url_repeat1] = aux_sym_url_repeat1,
  [aux_sym__group_repeat1] = aux_sym__group_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__start] = {
    .visible = false,
    .named = true,
  },
  [sym__range_start] = {
    .visible = false,
    .named = true,
  },
  [sym__run] = {
    .visible = false,
    .named = true,
  },
  [sym__tail] = {
    .visible = false,
    .named = true,
  },
  [sym__open] = {
    .visible = false,
    .named = true,
  },
  [sym__close] = {
    .visible = false,
    .named = true,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym__range_text] = {
    .visible = false,
    .named = true,
  },
  [sym_prose] = {
    .visible = true,
    .named = true,
  },
  [sym_url] = {
    .visible = true,
    .named = true,
  },
  [sym__part] = {
    .visible = false,
    .named = true,
  },
  [sym__group] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_prose_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_url_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__group_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 10,
  [14] = 11,
  [15] = 15,
  [16] = 8,
  [17] = 9,
  [18] = 18,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      if (eof) ADVANCE(1);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 1},
  [2] = {.lex_state = 0, .external_lex_state = 1},
  [3] = {.lex_state = 0, .external_lex_state = 1},
  [4] = {.lex_state = 0, .external_lex_state = 1},
  [5] = {.lex_state = 0, .external_lex_state = 1},
  [6] = {.lex_state = 0, .external_lex_state = 1},
  [7] = {.lex_state = 0, .external_lex_state = 1},
  [8] = {.lex_state = 0, .external_lex_state = 1},
  [9] = {.lex_state = 0, .external_lex_state = 1},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 2},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0, .external_lex_state = 2},
  [15] = {.lex_state = 0, .external_lex_state = 3},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__start] = ACTIONS(1),
    [sym__range_start] = ACTIONS(1),
    [sym__run] = ACTIONS(1),
    [sym__tail] = ACTIONS(1),
    [sym__open] = ACTIONS(1),
    [sym__close] = ACTIONS(1),
    [sym__text] = ACTIONS(1),
    [sym__range_text] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_prose] = STATE(18),
    [sym_url] = STATE(5),
    [aux_sym_prose_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__start] = ACTIONS(5),
    [sym__range_start] = ACTIONS(5),
    [sym__run] = ACTIONS(7),
    [sym__tail] = ACTIONS(7),
    [sym__open] = ACTIONS(7),
    [sym__close] = ACTIONS(7),
    [sym__text] = ACTIONS(7),
    [sym__range_text] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym__part] = STATE(3),
    [sym__group] = STATE(3),
    [aux_sym_url_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(9),
    [sym__start] = ACTIONS(11),
    [sym__range_start] = ACTIONS(9),
    [sym__run] = ACTIONS(11),
    [sym__tail] = ACTIONS(14),
    [sym__open] = ACTIONS(17),
    [sym__close] = ACTIONS(9),
    [sym__text] = ACTIONS(9),
    [sym__range_text] = ACTIONS(9),
  },
  [STATE(3)] = {
    [sym__part] = STATE(4),
    [sym__group] = STATE(4),
    [aux_sym_url_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(20),
    [sym__start] = ACTIONS(22),
    [sym__range_start] = ACTIONS(20),
    [sym__run] = ACTIONS(22),
    [sym__tail] = ACTIONS(25),
    [sym__open] = ACTIONS(28),
    [sym__close] = ACTIONS(20),
    [sym__text] = ACTIONS(20),
    [sym__range_text] = ACTIONS(20),
  },
  [STATE(4)] = {
    [sym__part] = STATE(4),
    [sym__group] = STATE(4),
    [aux_sym_url_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(31),
    [sym__start] = ACTIONS(33),
    [sym__range_start] = ACTIONS(31),
    [sym__run] = ACTIONS(33),
    [sym__tail] = ACTIONS(36),
    [sym__open] = ACTIONS(39),
    [sym__close] = ACTIONS(31),
    [sym__text] = ACTIONS(31),
    [sym__range_text] = ACTIONS(31),
  },
  [STATE(5)] = {
    [sym_url] = STATE(6),
    [aux_sym_prose_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(42),
    [sym__start] = ACTIONS(5),
    [sym__range_start] = ACTIONS(5),
    [sym__run] = ACTIONS(44),
    [sym__tail] = ACTIONS(44),
    [sym__open] = ACTIONS(44),
    [sym__close] = ACTIONS(44),
    [sym__text] = ACTIONS(44),
    [sym__range_text] = ACTIONS(44),
  },
  [STATE(6)] = {
    [sym_url] = STATE(6),
    [aux_sym_prose_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(46),
    [sym__start] = ACTIONS(48),
    [sym__range_start] = ACTIONS(48),
    [sym__run] = ACTIONS(51),
    [sym__tail] = ACTIONS(51),
    [sym__open] = ACTIONS(51),
    [sym__close] = ACTIONS(51),
    [sym__text] = ACTIONS(51),
    [sym__range_text] = ACTIONS(51),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(54),
    [sym__start] = ACTIONS(54),
    [sym__range_start] = ACTIONS(54),
    [sym__run] = ACTIONS(54),
    [sym__tail] = ACTIONS(54),
    [sym__open] = ACTIONS(54),
    [sym__close] = ACTIONS(54),
    [sym__text] = ACTIONS(54),
    [sym__range_text] = ACTIONS(54),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(56),
    [sym__start] = ACTIONS(56),
    [sym__range_start] = ACTIONS(56),
    [sym__run] = ACTIONS(56),
    [sym__tail] = ACTIONS(56),
    [sym__open] = ACTIONS(56),
    [sym__close] = ACTIONS(56),
    [sym__text] = ACTIONS(56),
    [sym__range_text] = ACTIONS(56),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(58),
    [sym__start] = ACTIONS(58),
    [sym__range_start] = ACTIONS(58),
    [sym__run] = ACTIONS(58),
    [sym__tail] = ACTIONS(58),
    [sym__open] = ACTIONS(58),
    [sym__close] = ACTIONS(58),
    [sym__text] = ACTIONS(58),
    [sym__range_text] = ACTIONS(58),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(62), 1,
      sym__open,
    ACTIONS(64), 1,
      sym__close,
    ACTIONS(60), 2,
      sym__run,
      sym__tail,
    STATE(11), 2,
      sym__group,
      aux_sym__group_repeat1,
  [15] = 4,
    ACTIONS(62), 1,
      sym__open,
    ACTIONS(68), 1,
      sym__close,
    ACTIONS(66), 2,
      sym__run,
      sym__tail,
    STATE(12), 2,
      sym__group,
      aux_sym__group_repeat1,
  [30] = 4,
    ACTIONS(73), 1,
      sym__open,
    ACTIONS(76), 1,
      sym__close,
    ACTIONS(70), 2,
      sym__run,
      sym__tail,
    STATE(12), 2,
      sym__group,
      aux_sym__group_repeat1,
  [45] = 4,
    ACTIONS(62), 1,
      sym__open,
    ACTIONS(80), 1,
      sym__close,
    ACTIONS(78), 2,
      sym__run,
      sym__tail,
    STATE(14), 2,
      sym__group,
      aux_sym__group_repeat1,
  [60] = 4,
    ACTIONS(62), 1,
      sym__open,
    ACTIONS(82), 1,
      sym__close,
    ACTIONS(66), 2,
      sym__run,
      sym__tail,
    STATE(12), 2,
      sym__group,
      aux_sym__group_repeat1,
  [75] = 3,
    ACTIONS(86), 1,
      sym__open,
    STATE(7), 1,
      sym__group,
    ACTIONS(84), 2,
      sym__start,
      sym__run,
  [86] = 1,
    ACTIONS(56), 4,
      sym__run,
      sym__tail,
      sym__open,
      sym__close,
  [93] = 1,
    ACTIONS(58), 4,
      sym__run,
      sym__tail,
      sym__open,
      sym__close,
  [100] = 1,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 15,
  [SMALL_STATE(12)] = 30,
  [SMALL_STATE(13)] = 45,
  [SMALL_STATE(14)] = 60,
  [SMALL_STATE(15)] = 75,
  [SMALL_STATE(16)] = 86,
  [SMALL_STATE(17)] = 93,
  [SMALL_STATE(18)] = 100,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prose, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_url, 1, 0, 0),
  [11] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_url, 1, 0, 0), SHIFT(3),
  [14] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_url, 1, 0, 0), SHIFT(15),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_url, 1, 0, 0), SHIFT(10),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_url, 2, 0, 0),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_url, 2, 0, 0), SHIFT(4),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_url, 2, 0, 0), SHIFT(15),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_url, 2, 0, 0), SHIFT(10),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_url_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_url_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_url_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_url_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prose, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_prose_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_prose_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_prose_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__part, 2, 1, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__group, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__group, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__group_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__group_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__group_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [88] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__start = 0,
  ts_external_token__range_start = 1,
  ts_external_token__run = 2,
  ts_external_token__tail = 3,
  ts_external_token__open = 4,
  ts_external_token__close = 5,
  ts_external_token__text = 6,
  ts_external_token__range_text = 7,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start] = sym__start,
  [ts_external_token__range_start] = sym__range_start,
  [ts_external_token__run] = sym__run,
  [ts_external_token__tail] = sym__tail,
  [ts_external_token__open] = sym__open,
  [ts_external_token__close] = sym__close,
  [ts_external_token__text] = sym__text,
  [ts_external_token__range_text] = sym__range_text,
};

static const bool ts_external_scanner_states[4][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start] = true,
    [ts_external_token__range_start] = true,
    [ts_external_token__run] = true,
    [ts_external_token__tail] = true,
    [ts_external_token__open] = true,
    [ts_external_token__close] = true,
    [ts_external_token__text] = true,
    [ts_external_token__range_text] = true,
  },
  [2] = {
    [ts_external_token__run] = true,
    [ts_external_token__tail] = true,
    [ts_external_token__open] = true,
    [ts_external_token__close] = true,
  },
  [3] = {
    [ts_external_token__start] = true,
    [ts_external_token__run] = true,
    [ts_external_token__open] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_hyperlink_external_scanner_create(void);
void tree_sitter_hyperlink_external_scanner_destroy(void *);
bool tree_sitter_hyperlink_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_hyperlink_external_scanner_serialize(void *, char *);
void tree_sitter_hyperlink_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hyperlink(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_hyperlink_external_scanner_create,
      tree_sitter_hyperlink_external_scanner_destroy,
      tree_sitter_hyperlink_external_scanner_scan,
      tree_sitter_hyperlink_external_scanner_serialize,
      tree_sitter_hyperlink_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "hyperlink",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
